### ISSUE TITLE
ModuleNotFoundError: No module named 'sage'

### ISSUE THREAD

**Issue by Rowing0914** [demining/CryptoDeepTools#24]
After going through your README, I'm still getting the ModulenotFoundError.

```shell
Traceback (most recent call last):
  File "/content/SageMath/discrete.py", line 1, in <module>
    from sage.all import *
ModuleNotFoundError: No module named 'sage'
```

is readme up to date?

**Comment by demining** [comment]
### Run command:
`yes '' | sudo env DEBIAN_FRONTEND=noninteractive apt-get -y -o DPkg::options::="--force-confdef" -o DPkg::options::="--force-confold" install sagemath`

### Then check:
`sage -v`

**Comment by Rowing0914** [comment]
Thank you!
